name: Check

on:
  workflow_dispatch:
  commit:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9.6
      
      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: ./check.sh